### ISSUE TITLE
b3dm file sizes should be a multiple of 8 bytes

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-samples-generator#1]
In https://github.com/CesiumGS/3d-tiles/issues/446 @renjianqiang pointed out that [batchColors.b3dm](https://github.com/CesiumGS/cesium/blob/master/Apps/SampleData/Cesium3DTiles/Batched/BatchedColors/batchedColors.b3dm) has a byte length of 13316 which is not 8-byte aligned as required by the Batched 3D Model format [here](https://github.com/CesiumGS/3d-tiles/tree/master/specification/TileFormats/Batched3DModel#padding). This and any other b3dm's having this problem should be fixes in samples-generator.

**Comment by javagl** [comment]
The changes that affect the samples-generator are part of https://github.com/CesiumGS/3d-tiles-validator/pull/212 and could be integrated here. The linked PR will be closed, because the changes that affect the validator are now part of https://github.com/CesiumGS/3d-tiles-validator/pull/223
